steps:
- task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2022
  displayName: 'Application security testing'
  inputs:
    projectName: 'Pritesh-ADO'
    syncMode: true
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 9.4SAST
    sastProxyUrl: ''
    preset: Checkmarx Default
    customPreset: 'All'
    engineConfigId: 
    fullTeamName: /CxServer
    sastCaChainFilePath: ''
    overrideProjectSettings: false
    incScan: true
    fullScansScheduled: true
    fullScanCycle: 5
    forceScan: false
    folderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules'
    fileExtension: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules'
    manifestPattern: **/folder1/**, !**test.yaml
    fingerprintPattern: **/folder1/**, !**test.yaml
    projectCustomTags: ‘ENV: DEV', ‘Team: ’
    scanCustomTags: ‘ENV: DEV', ‘Team: ’
    scaScanTimeout:
    scanTimeout: 5
    projectcustomfields: ''
    customfields: ''
    denyProject: false
    comment: 'Sample YAML File'
    postScanAction: 
    generatePDFReport: true
    vulnerabilityThreshold: false
    failBuildForNewVulnerabilitiesEnabled: true
    failBuildForNewVulnerabilitiesSeverity: MEDIUM
    high: 10
    medium: 10
    low: 10
    enablePolicyViolations: false
    avoidDuplicateScans: false
    enableDependencyScan: true
    dependencyServerURL: 'SCA'
    scaProxyUrl: ''
    dependencyFileExtension: ''
    dependencyFolderExclusion: ''
    scaTeam: /CxServer
    scaCaChainFilePath: c://Users
    scaConfigFilePaths: ''
    scaEnvVariables: ''
    isEnableScaResolver: true
    scaResolverAddParameters: ''
    includeSource: true
    scaExploitablePath: true
    pathToScaResolver: ‘C:\Users\PriteshP\Downloads\ScaResolver-2.12.3’
    CheckmarxServiceForSca: 9.4SAST
    scaProjectFullPath: c://Users
    scaProjectId: 1
    scaEnablePolicyViolations: false
    scaVulnerabilityThreshold: false
    scaHigh: 10
    scaMedium: 10
    scaLow: 10
    enableSastBranching :true
    masterBranchProjectName : ''
    waitingTimeBeforeRetryScan :30
    critical: 10
    waitingTimeBeforeRetrySCAScan:30
    scaCritical: 10